import { Resend } from "resend";
import type { WeeklyDigest } from "@prisma/client";
import type { DigestItem } from "@/lib/types";

const SUBJECT = "Startup Digest: This Week's Product Ideas";

function asItems(value: unknown): DigestItem[] {
  if (!Array.isArray(value)) return [];
  return value.filter(
    (v): v is DigestItem =>
      !!v && typeof v === "object" && "productId" in v && "name" in v
  );
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function renderSection(heading: string, items: DigestItem[]): string {
  const safeHeading = escapeHtml(heading);
  if (!items.length) {
    return `
      <h2 style="font-size:18px;margin:28px 0 8px;color:#0f172a;">${safeHeading}</h2>
      <p style="color:#64748b;margin:0 0 8px;font-size:14px;">No items this week.</p>`;
  }

  const rows = items
    .map(
      (it) => `
      <tr>
        <td style="padding:14px 0;border-bottom:1px solid #e2e8f0;">
          <a href="${escapeHtml(it.detailUrl)}" style="font-size:15px;font-weight:600;color:#0f172a;text-decoration:none;">
            ${escapeHtml(it.name)}
          </a>
          <div style="color:#475569;font-size:13px;margin:2px 0 6px;">${escapeHtml(it.tagline)}</div>
          <div style="font-size:12px;color:#64748b;">
            <span style="display:inline-block;background:#dcfce7;color:#166534;border-radius:6px;padding:2px 8px;margin-right:6px;font-weight:600;">Opportunity ${it.opportunityScore}/100</span>
            <span style="display:inline-block;background:#f1f5f9;border-radius:6px;padding:2px 8px;margin-right:6px;">Clone ${it.cloneScore}/10</span>
            <span style="display:inline-block;background:#f1f5f9;border-radius:6px;padding:2px 8px;margin-right:6px;">Difficulty ${it.buildDifficulty}/10</span>
            <span style="display:inline-block;background:#f1f5f9;border-radius:6px;padding:2px 8px;">MVP: ${escapeHtml(it.mvpTime)}</span>
          </div>
          ${
            it.founderTake
              ? `<div style="font-size:13px;color:#334155;margin-top:8px;font-style:italic;">"${escapeHtml(it.founderTake)}"</div>`
              : ""
          }
          <div style="margin-top:8px;">
            <a href="${escapeHtml(it.detailUrl)}" style="font-size:12px;color:#2563eb;text-decoration:none;">View details &rarr;</a>
          </div>
        </td>
      </tr>`
    )
    .join("");

  return `
    <h2 style="font-size:18px;margin:28px 0 4px;color:#0f172a;">${safeHeading}</h2>
    <table width="100%" cellpadding="0" cellspacing="0" role="presentation">${rows}</table>`;
}

export function renderDigestHtml(digest: WeeklyDigest): string {
  const worth = asItems(digest.topWorthBuilding);
  const niche = asItems(digest.topNicheIdeas);
  const ai = asItems(digest.topAiIdeas);
  const easy = asItems(digest.easyBuildIdeas);

  return `<!doctype html>
<html>
  <body style="margin:0;background:#f8fafc;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
    <div style="max-width:620px;margin:0 auto;padding:32px 24px;">
      <div style="background:#ffffff;border:1px solid #e2e8f0;border-radius:14px;padding:32px;">
        <p style="font-size:12px;letter-spacing:0.08em;text-transform:uppercase;color:#94a3b8;margin:0 0 6px;">Startup Digest</p>
        <h1 style="font-size:22px;margin:0 0 6px;color:#0f172a;">${escapeHtml(digest.title)}</h1>
        <p style="font-size:14px;color:#475569;margin:0 0 8px;">${escapeHtml(digest.summary)}</p>
        ${renderSection("🚀 Top 5 Products Worth Building", worth)}
        ${renderSection("🎯 Top 5 Niche Opportunities", niche)}
        ${renderSection("🤖 Top 5 AI Upgrade Ideas", ai)}
        ${renderSection("⚡ Top 5 Easy MVP Builds", easy)}
        <hr style="border:none;border-top:1px solid #e2e8f0;margin:28px 0 16px;" />
        <p style="font-size:12px;color:#94a3b8;margin:0;">Generated by your Startup Digest founder tool.</p>
      </div>
    </div>
  </body>
</html>`;
}

/**
 * Send a weekly digest email via Resend.
 * Returns { sent, id?, error? } without throwing so callers can record outcome.
 */
export async function sendDigestEmail(
  digest: WeeklyDigest
): Promise<{ sent: boolean; id?: string; error?: string }> {
  const apiKey = process.env.RESEND_API_KEY;
  const to = process.env.DIGEST_EMAIL_TO;
  const from =
    process.env.DIGEST_EMAIL_FROM || "Startup Digest <onboarding@resend.dev>";

  if (!apiKey) {
    return { sent: false, error: "RESEND_API_KEY is not configured." };
  }
  if (!to) {
    return { sent: false, error: "DIGEST_EMAIL_TO is not configured." };
  }

  try {
    const resend = new Resend(apiKey);
    const { data, error } = await resend.emails.send({
      from,
      to,
      subject: SUBJECT,
      html: renderDigestHtml(digest),
    });

    if (error) {
      console.error("[email] Resend error:", error);
      return { sent: false, error: error.message };
    }

    return { sent: true, id: data?.id };
  } catch (err) {
    console.error("[email] send failed:", err);
    return {
      sent: false,
      error: err instanceof Error ? err.message : "Unknown email error",
    };
  }
}
